### ISSUE TITLE
error while running the script

### ISSUE THREAD

**Issue by FloatingLizard** [chander/social-network-cleaner#6]
Hello,

  Everytime I run the script I get this error.  I initially thought that it was the add-ons.  What is causing this?    I had it working one time and then this.  Is there a time window?

Traceback (most recent call last):
  File "cleaner.py", line 954, in <module>
    min_date=options.min_date)
  File "cleaner.py", line 755, in clean_posts
    feed = self.graphLookup("me", "feed")  # requires read_stream
  File "cleaner.py", line 133, in graphLookup
    return self.graph.get_connections(_args, *_kwargs)
  File "cleaner.py", line 83, in graph
    token = self.get_api_token()
  File "cleaner.py", line 730, in get_api_token
    elem = self.driver.find_element_by_id("access_token")
  File "/home/coper/social-network-cleaner/social-network-cleaner-master/venv/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/home/coper/social-network-cleaner/social-network-cleaner-master/venv/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 664, in find_element
    {'using': by, 'value': value})['value']
  File "/home/coper/social-network-cleaner/social-network-cleaner-master/venv/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 175, in execute
    self.error_handler.check_response(response)
  File "/home/coper/social-network-cleaner/social-network-cleaner-master/venv/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 166, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: {"method":"id","selector":"access_token"}
Stacktrace:
    at FirefoxDriver.prototype.findElementInternal_ (file:///tmp/tmpabeFoX/extensions/fxdriver@googlecode.com/components/driver-component.js:10271)
    at FirefoxDriver.prototype.findElement (file:///tmp/tmpabeFoX/extensions/fxdriver@googlecode.com/components/driver-component.js:10280)
    at DelayedCommand.prototype.executeInternal_/h (file:///tmp/tmpabeFoX/extensions/fxdriver@googlecode.com/components/command-processor.js:12274)
    at DelayedCommand.prototype.executeInternal_ (file:///tmp/tmpabeFoX/extensions/fxdriver@googlecode.com/components/command-processor.js:12279)
    at DelayedCommand.prototype.execute/< (file:///tmp/tmpabeFoX/extensions/fxdriver@googlecode.com/components/command-processor.js:12221)

**Comment by marvinandro** [comment]
I'm on the same boat. Any chance you could help?

**Comment by FloatingLizard** [comment]
I can not help on this!  i accidentally forked myself into this.  But anyhow the other switches do work!   But I think that there have been some changes on FB side that is causing the error when running the --posts switch.

**Comment by marvinandro** [comment]
Thanks @jpalcantara! 
I was hoping @chander would help both of us :)

**Comment by chander** [comment]
They changed the format of the API key page to make it harder to generate and grab the token data...

**Comment by chander** [comment]
Please reopen this if it's not fixed, but it should work now..

**Comment by FloatingLizard** [comment]
I just tried and I still have the same problem as above.

**Comment by chander** [comment]
If you do a "git log" do you see my recent checkins?  If you forked, then you'll need to merge in my changes to your branch...

Otherwise, the full traceback of your error would be useful to have.

**Comment by marvinandro** [comment]
Thank you, @chander! Now I'm watching the magic happen.

**Comment by jpalcantara** [comment]
No magic here same exact error same exact error as posted above  @marvinandro

**Comment by chander** [comment]
@jpalcantara : with these changes the line referenced in the error actually no longer exists in the code.  If you're getting that same error, then you aren't using the latest code (i.e., you don't have the update.)

**Comment by chander** [comment]
The old code like 730 has been removed (referenced in the traceback above):
elem = self.driver.find_element_by_id("access_token")

with the new code, which ought to have something like this (instead):
elem = self.driver.find_elements_by_xpath( "//span[contains(text(), 'Access Token')]/following::input[1]")[0]

If you're seeing that old error, then you don't have the latest code.

**Comment by FloatingLizard** [comment]
I am sorry, I spaced out!  It is working 828 post going to be deleted.  Thank you :)
